.TH "Visitor" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Visitor \- Represents a \fBVisitor\fP structure with entering and leaving time\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBenteringTime\fP"
.br
.RI "The entering time of the visitor\&. "
.ti -1c
.RI "std::string \fBleavingTime\fP"
.br
.RI "The leaving time of the visitor\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a \fBVisitor\fP structure with entering and leaving time\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
